-- CREATE OR REPLACE TRIGGER T
-- BEFORE INSERT ON ITEM FOR EACH ROW
-- DECLARE
-- BEGIN
-- IF(:NEW.SOH>:NEW.ROL)THEN
-- RAISE_APPLICATION_ERROR(-21000, 'SOH VALUE SHOULD BE LESS THAN ROL');
-- END IF;
-- END;
-- /

CREATE OR REPLACE TRIGGER T
BEFORE 